# Generated by Django 5.0 on 2023-12-09 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='asdsvbhvdsahbvadshbadsfvb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='sjadbjavdsbj', max_length=100),
            preserve_default=False,
        ),
    ]
